
language: python
python:
  - "3.9"

before_install:
  - python -m pip install --upgrade pip
script:
  - python -m pytest -v tests/
  - pylint app
after_success:
  - COVERALLS_REPO_TOKEN=gjAlZt9Z9T8kZAVtoPpZ6HtOqCM4DmL4t coveralls

